apk add nghttp2-static nghttp2-dev openssl-libs-static openssl-dev libcrypto1.1 cmake boost-static boost-dev luajit-dev gcc g++ unzip wget libexecinfo-dev libexecinfo-static make && \
wget https://github.com/Tencent/rapidjson/archive/refs/heads/master.zip && \
unzip master.zip && \
cd rapidjson-master && cmake . && cmake --build ./ && cmake --install ./ && \
cd .. && \
rm rapidjson-master master.zip -rf && \
wget https://github.com/wallyatgithub/h2loadrunner/archive/refs/heads/main.zip && \
unzip main.zip && \
cmake -S h2loadrunner-main -B h2loadrunner-main/build -DCMAKE_BUILD_TYPE=Release .. -DALPINE_STATIC=ON && \
cmake --build h2loadrunner-main/build && \
cp h2loadrunner-main/build/h2loadrunner /usr/bin/ && \
mkdir -p /usr/share/h2loadrunner/ && \
cp h2loadrunner-main/config_schema.json /usr/share/h2loadrunner/ && \
rm -rf h2loadrunner-main main.zip &&
apk del nghttp2-static nghttp2-dev openssl-libs-static openssl-dev libcrypto1.1 cmake boost-static boost-dev luajit-dev gcc g++ unzip wget libexecinfo-dev libexecinfo-static make