FROM amd64/centos:7
RUN yum update -y && \
    yum install openssl-devel libev-devel make unzip wget -y && \
    yum install epel-release -y && \
    yum install luajit-devel libnghttp2-devel rapidjson-devel cmake3 -y && \
    yum install centos-release-scl -y && \
    yum install devtoolset-8-gcc devtoolset-8-gcc-c++ -y && \
    wget https://github.com/wallyatgithub/h2loadrunner/archive/refs/heads/main.zip && \
    unzip main.zip && \
    scl enable devtoolset-8 -- cmake3 -S h2loadrunner-main/third-party/c-ares -B h2loadrunner-main/third-party/c-ares && \
    scl enable devtoolset-8 -- cmake3 --build h2loadrunner-main/third-party/c-ares && \
    scl enable devtoolset-8 -- mkdir h2loadrunner-main/build && \
    scl enable devtoolset-8 -- cmake3 -S h2loadrunner-main -B h2loadrunner-main/build && \
    scl enable devtoolset-8 -- cmake3 --build h2loadrunner-main/build && \
    yum remove git make unzip wget cmake3 devtoolset-8-gcc devtoolset-8-gcc-c++ centos-release-scl -y && \
    cp h2loadrunner-main/build/h2loadrunner /usr/bin/ && \
    mkdir -p /usr/share/h2loadrunner/ && \
    cp h2loadrunner-main/config_schema.json /usr/share/h2loadrunner/ && \
    rm -rf h2loadrunner-main main.zip
