FROM ubuntu:latest
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata && \
    apt-get install --yes libnghttp2-dev openssl libssl-dev libev-dev liblua5.3-dev rapidjson-dev cmake build-essential libboost-all-dev libluajit-5.1-dev gcc g++ unzip wget && \
    wget https://github.com/wallyatgithub/h2loadrunner/archive/refs/heads/main.zip && \
    unzip main.zip && \
    cmake -S h2loadrunner-main/third-party/c-ares -B h2loadrunner-main/third-party/c-ares && \
    cmake --build h2loadrunner-main/third-party/c-ares && \
    mkdir h2loadrunner-main/build && \
    cmake -S h2loadrunner-main -B h2loadrunner-main/build && \
    cmake --build h2loadrunner-main/build && \
    apt-get remove --yes cmake build-essential gcc g++ unzip libboost-all-dev && \
    apt-get autoremove --yes && \
    cp h2loadrunner-main/build/h2loadrunner /usr/bin/ && \
    mkdir -p /usr/share/h2loadrunner/ && \
    cp h2loadrunner-main/config_schema.json /usr/share/h2loadrunner/ && \
    rm -rf h2loadrunner-main main.zip
